# config/packages/salons.yaml
App\Entity\Salons:
  properties:
    dateVote:
      type: DateTime
      options:
        label: "Delais"
        widget: single_text
        format: 'dd-MM-yyyy HH:mm'
        attr:
          placeholder: 'JJ-MM-AAAA HH:mm'
        constraints:
          NotBlank:
            message: "Veuillez saisir une date de clôture."
          DateTime:
            - GreaterThan :