framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false

#App\Entity\Salons:
#    properties:
#        dateVote:
#            type: DateTime
#            options:
#                label: "Delais"
#                widget: single_text
#                format: 'dd-MM-yyyy HH:mm'
#                attr:
#                    placeholder: 'JJ-MM-AAAA HH:mm'
#                constraints:
#                    NotBlank:
#                        message: "Veuillez saisir une date de clôture."
#                    DateTime:
#                        - GreaterThan :
#                              value: "@datetime.now|date_modify('-1 hour')|format('d-m-Y H:m')"
#                              message: "La date paramétrée doit être supérieure à la date actuelle"